repos:

  - repo: local
    hooks:

      - id: isort
        name: isort
        entry: poetry run isort --profile black
        language: system
        types: [python]

      - id: ruff
        name: ruff
        entry: poetry run ruff format
        language: system
        types: [python]

      - id: ruff
        name: ruff
        entry: poetry run ruff check --fix
        language: system
        types: [python]
