name: Test Release

on:
  push:
    branches:
      - main

jobs:
  sanity-check:
    name: Build and Verify Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Ensure ~/.casa/data exists
        run: mkdir -p ~/.casa/data

      - name: Build package
        run: |
          poetry install --no-root
          poetry build

      - name: Check artifacts with twine
        run: |
          pip install twine
          twine check dist/*

      - name: Create test venv and install package
        run: |
          python -m venv testenv
          source testenv/bin/activate
          pip install dist/*.whl

          python -c "import dstools"

          dstools-extract-ds --help || echo "No CLI tool found"

      - name: Clean up
        if: always()
        run: rm -rf testenv
